### PR TITLE
Implement Real-Debrid speedtest functionality to optimize CDN selection

### PR DESCRIPTION
**Pull request by Arshit-Singhal-Official**
Added Real-Debrid Speedtest functionality to MediaFlow as discussed in the Elf-Hosted Discord. The endpoint for this feature is /speedtest?api_password=your_password, ensuring protection against unauthorized triggers. The Speedtest data will remain active for one hour.

The implementation utilizes the requests module, which I have added to pyproject.toml, and the lock file has been generated accordingly. It is necessary to include this module in the MediaFlow-proxy pip package.

### CODE REVIEW

**Comment by mhdzumair** [comment]
Thanks for your contribution. i change the target branch, so ill do the modification on it later.

**Comment by Arshit-Singhal-Official** [comment]
Ok thank you, if you need any changes to be done please ask.

**Comment by mhdzumair** [comment]
i was planned to change the function to utilize the Streamer class streaming function instead of using the request in order to correctly find the speed test.

**Comment by Arshit-Singhal-Official** [comment]
ok let me try and do that you are talking about the one from the https utils file right?

**Pull request merged**
